[package]
name = "delegator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "delegator"
path = "src/main.rs"

[lib]
name = "delegator_core"
path = "src/core/core.rs"

[dependencies]
actix-web = "4.2.1"
awc = "3.0.1"
derive_more = "0.99.17"
env_logger = "0.9.3"
hocon = "0.9.0"
http-serde = "1.1.2"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0"
