[package]
name = "delegator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "delegator"
path = "src/main.rs"

[lib]
name = "delegator_core"
path = "src/core/core.rs"

[dependencies]
actix-web = "4.3.1"
async-trait = "0.1.67"
awc = { version = "3.1.1", features = ["openssl"] }
derive_more = "0.99.17"
env_logger = "0.10.0"
hashbrown = { version = "0.13.2", features = ["serde"] }
hocon = "0.9.0"
http-serde = "1.1.2"
nom = { version = "7.1.3", features = [ "alloc" ] }
once_cell = "1.17.1"
sentry = "0.29.3"
sentry-actix = "0.30.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0"
