name: Auto Lint, Build, and Test

on:
  push:
    branches-ignore:
      - master

jobs:
  call-lint-build-test:
    uses: ./.github/workflows/mod-lint-build-test.yml
    secrets: 
      CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}

  check-terraform:
    uses: ./.github/workflows/mod-deploy-to-env.yml
    with:
      environment  : stag
      aws_region   : us-east-1
      app_image_tag: this-is-not-a-valid-tag
      do_dry_run   : true
    secrets:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI_ACCESS_TOKEN      : ${{ secrets.CI_ACCESS_TOKEN }}
