name: Auto Security Audit

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 0 * * *'

jobs:
  call-security-audit:
    uses: ./.github/workflows/mod-security-audit.yml
    secrets:
      CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
