name: Auto Lint, Build, and Test

on:
  push:
    branches-ignore:
      - master

jobs:
  call-lint-build-test:
    uses: ./.github/workflows/mod-lint-build-test.yml
    secrets: 
      CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
