name: Auto Build, Test, Push, Deploy

on:
  push:
    branches:
      - master

jobs:
  call-build-test-push-deploy:
    uses: ./.github/workflows/mod-build-test-push-deploy.yml
    with:
      environment: stag
      aws_region : us-east-1
      do_dry_run : false
    secrets:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI_ACCESS_TOKEN      : ${{ secrets.CI_ACCESS_TOKEN }}
      SENTRY_BEARER_TOKEN  : ${{ secrets.SENTRY_BEARER_TOKEN }}
