name: Manual Build, Test, Push, Deploy

on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment in which to deploy the API and DB Migrations images.'
        type: choice
        default: stag
        required: true
        options:
          - stag
          - thunderdome
          - prod
      aws_region:
        description: 'The AWS Region in which to deploy the API and DB Migrations images.'
        required: true
        type: choice
        default: us-east-1
        options:
          - us-east-1

jobs:
  call-build-test-push-deploy:
    uses: ./.github/workflows/mod-build-test-push-deploy.yml
    with:
      environment  : ${{ inputs.environment || 'stag' }}
      aws_region   : ${{ inputs.aws_region || 'us-east-1' }}
    secrets:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI_ACCESS_TOKEN      : ${{ secrets.CI_ACCESS_TOKEN }}
      SENTRY_BEARER_TOKEN  : ${{ secrets.SENTRY_BEARER_TOKEN }}
