name: CD

on:
  push:
    branches:
      - master

  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      environment:
        description: "The environment in which to deploy."
        type: choice
        default: stag
        required: true
        options:
          - stag
          - thunderdome
          - prod
      aws_region:
        description: "The AWS Region in which to deploy."
        required: true
        type: choice
        default: us-east-1
        options:
          - us-east-1

env:
  GITHUB_TOKEN         : ${{ secrets.CI_ACCESS_TOKEN }}

jobs:
  docker-build-push:
    name: Build, push
    uses: Appreciate-Stuff/appreciate-actions/.github/workflows/docker-build-push.yml@3e6542ca598cef504da493963458f9173f91f68c # v1.0.1
    with:
      image_name: delegator
      push      : true
      migrations: false
      build_args: |
        RUST_STAGE=release
        CARGO_ARGS=--release
    secrets:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  sentry-release:
    runs-on: ubuntu-latest
    name: Release
    needs:
      - docker-build-push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          depth: 0
      - name: Sentry Release
        uses: getsentry/action-release@4744f6a65149f441c5f396d5b0877307c0db52c7  # v1.4.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_BEARER_TOKEN }}
          SENTRY_ORG: appreciate-stuff
          SENTRY_PROJECT: delegator
        with:
          ignore_missing: true
          ignore_empty: true
          version: delegator-${{ needs.docker-build-push.outputs.tag }}

  call-deploy-to-env:
    uses: Appreciate-Stuff/appreciate-actions/.github/workflows/deploy.yml@3e6542ca598cef504da493963458f9173f91f68c # v1.0.1
    needs:
      - docker-build-push
    with:
      environment       : ${{ inputs.environment || 'stag' }}
      aws_region        : ${{ inputs.aws_region || 'us-east-1' }}
      image_tag         : ${{ needs.docker-build-push.outputs.tag }}
      apply             : true
      migrations        : false
    secrets:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI_ACCESS_TOKEN      : ${{ secrets.CI_ACCESS_TOKEN }}

  sentry-deploy:
    uses: Appreciate-Stuff/appreciate-actions/.github/workflows/sentry-api.yml@3e6542ca598cef504da493963458f9173f91f68c  # v1.0.1
    needs:
      - docker-build-push
      - call-deploy-to-env
    with:
      organization_slug: appreciate-stuff
      route            : releases/delegator-${{ needs.docker-build-push.outputs.tag }}/deploys/
      curl_args        : -d '{"environment":"${{ inputs.environment || 'stag' }}"}'
    secrets:
      SENTRY_BEARER_TOKEN: ${{ secrets.SENTRY_BEARER_TOKEN }}
