name: CD

on:
  push:
    branches:
      - master

  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment in which to deploy.'
        type: choice
        default: stag
        required: true
        options:
          - stag
          - thunderdome
          - prod
      aws_region:
        description: 'The AWS Region in which to deploy.'
        required: true
        type: choice
        default: us-east-1
        options:
          - us-east-1

env:
  MASTER_BRANCH        : master
  AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GITHUB_TOKEN         : ${{ secrets.CI_ACCESS_TOKEN }}
  SENTRY_BEARER_TOKEN  : ${{ secrets.SENTRY_BEARER_TOKEN }}

jobs:
  build-push:
    name: Build, push
    uses: Appreciate-Stuff/appreciate-actions/.github/workflows/docker-build-push.yml@702581b456499eb972f07b093b325f5efaa7dbfd  # v0.1.1
    with:
      image_name: delegator
      push: true
      build_args: |
        RUST_STAGE=release
        CARGO_ARGS=--release
    secrets:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  call-deploy-to-env:
    uses: Appreciate-Stuff/appreciate-actions/.github/workflows/deploy.yml@702581b456499eb972f07b093b325f5efaa7dbfd  # v0.1.1
    needs:
      - build-push
    with:
      environment  : ${{ inputs.environment || 'stag' }}
      aws_region   : ${{ inputs.aws_region || 'us-east-1' }}
      app_image_tag: ${{ needs.build-push.outputs.tag }}
    secrets:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI_ACCESS_TOKEN      : ${{ secrets.CI_ACCESS_TOKEN }}
