name: CI

on:
  push:
    branches-ignore:
      - master

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3

      - name: Install rust stable
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af  # v1.0.7
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Set up build cache
        uses: swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894  # v2.4.0

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVKEY }}

      - name: Check workflow permissions
        id: check_permissions
        uses: scherermichael-oss/action-has-permission@136e061bfe093832d87f090dd768e14e27a740d3  # v1.0.6
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Run clippy check
        uses: actions-rs/clippy-check@b5b5f21f4797c02da247df37026fcd0a5024aa4d  # v1.0.7
        if: steps.check_permissions.outputs.has-permission
        with:
          token: ${{ steps.app-token.outputs.token }}
          args: -- -D warnings

      - name: Run tests
        run: cargo test

#  Tarpaulin is a code coverage tool, but it can't differentiate between our
#  code and our library code, so it ends up rebuilding everything from scratch
#  every CI run.
#
#  Possibly enable this on merge to master, but we're not consuming these
#  metrics right now so disable it and save some build credits.
#
#  tarpaulin:
#    name: tarpaulin
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Install rust stable
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          override: true
#
#      - name: Set up build cache
#        uses: swatinem/rust-cache@v2
#
#      - name: Install tarpaulin
#        run: cargo install cargo-tarpaulin
#
#      - name: Run cargo tarpaulin
#        uses: actions-rs/cargo@v1
#        with:
#          command: tarpaulin
