name: Manual Deploy to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment in which to deploy.'
        type: choice
        default: stag
        required: true
        options:
          - stag
          - thunderdome
          - prod
      aws_region:
        description: 'The AWS Region in which to deploy.'
        required: true
        type: choice
        default: us-east-1
        options:
          - us-east-1
      app_image_tag:
        description: 'The Docker image tag of the image to deploy.'
        type: string
        required: true
      apply:
        description: 'Uncheck to only run the plan.'
        default: true
        type: boolean 

jobs:
  call-deploy-to-env:
    uses: Appreciate-Stuff/appreciate-actions/.github/workflows/deploy.yml@702581b456499eb972f07b093b325f5efaa7dbfd  # v0.1.1
    with:
      environment  : ${{ inputs.environment }}
      aws_region   : ${{ inputs.aws_region }}
      app_image_tag: ${{ inputs.app_image_tag }}
      apply        : ${{ inputs.apply }}
    secrets:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI_ACCESS_TOKEN      : ${{ secrets.CI_ACCESS_TOKEN }}

  # call-publish-release-metadata:
  #   uses: ./.github/workflows/callable_publish_release_metadata.yml
  #   needs:
  #     - call-deploy-to-env
  #   with:
  #     version: ${{ inputs.api_image_tag }}
  #     environment: ${{ inputs.environment }}
  #   secrets:
  #     SENTRY_BEARER_TOKEN: ${{ secrets.SENTRY_BEARER_TOKEN }}
