name: Deploy Service
run-name: |
  ${{ inputs.environment }}${{ inputs.apply && ': ' || ' (Dry run): ' }}${{ inputs.image_tag }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment in which to deploy."
        type: choice
        default: stag
        required: true
        options:
          - stag
          - thunderdome
          - prod
      aws_region:
        description: "The AWS Region in which to deploy."
        required: true
        type: choice
        default: us-east-1
        options:
          - us-east-1
      image_tag:
        description: "The Docker image tag of the image to deploy."
        type: string
        required: true
      apply:
        description: "Uncheck to only run the plan."
        default: true
        type: boolean

jobs:
  deploy:
    uses: Appreciate-Stuff/appreciate-actions/.github/workflows/deploy.yml@3e6542ca598cef504da493963458f9173f91f68c # v1.0.1
    with:
      environment       : ${{ inputs.environment }}
      aws_region        : ${{ inputs.aws_region }}
      image_tag         : ${{ inputs.image_tag }}
      apply             : ${{ inputs.apply }}
      migrations        : false

    secrets:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI_ACCESS_TOKEN      : ${{ secrets.CI_ACCESS_TOKEN }}

  release:
    uses: Appreciate-Stuff/appreciate-actions/.github/workflows/sentry-api.yml@3e6542ca598cef504da493963458f9173f91f68c  # v1.0.1
    needs:
      - deploy
    with:
      organization_slug: appreciate-stuff
      route            : releases/delegator@${{ inputs.image_tag }}/deploys/
      curl_args        : -d '{"environment":"${{ inputs.environment }}"}'
    secrets:
      SENTRY_BEARER_TOKEN: ${{ secrets.SENTRY_BEARER_TOKEN }}
