name: Manual Build, Test, Push

on: 
  workflow_dispatch:

jobs:
  call-build-test-push:
    uses: ./.github/workflows/mod-build-test-push.yml
    secrets:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI_ACCESS_TOKEN      : ${{ secrets.CI_ACCESS_TOKEN }}
      SENTRY_BEARER_TOKEN  : ${{ secrets.SENTRY_BEARER_TOKEN }}
