name: Manual Deploy to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment in which to deploy the API and DB Migrations images.'
        type: choice
        default: stag
        required: true
        options:
          - stag
          - thunderdome
          - prod
      aws_region:
        description: 'The AWS Region in which to deploy the API and DB Migrations images.'
        required: true
        type: choice
        default: us-east-1
        options:
          - us-east-1
      app_image_tag:
        description: 'The Docker image tag of the image to deploy.'
        type: string
        required: true
      do_dry_run:
        description: 'If true, then terragrunt apply will not be run -- only plan.  No changes will be made to our infrastructure.'
        default: true
        type: boolean 

jobs:
  call-deploy-to-env:
    uses: ./.github/workflows/mod-build-test-push-deploy.yml
    with:
      environment  : ${{ inputs.environment }}
      aws_region   : ${{ inputs.aws_region }}
      app_image_tag: ${{ inputs.app_image_tag }}
      do_dry_run   : ${{ inputs.do_dry_run }}
    secrets:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # call-publish-release-metadata:
  #   uses: ./.github/workflows/callable_publish_release_metadata.yml
  #   needs:
  #     - call-deploy-to-env
  #   with:
  #     version: ${{ inputs.api_image_tag }}
  #     environment: ${{ inputs.environment }}
  #   secrets:
  #     SENTRY_BEARER_TOKEN: ${{ secrets.SENTRY_BEARER_TOKEN }}
