name: Security audit

on:
  workflow_call:
    secrets:
      CI_ACCESS_TOKEN:
        required: true

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.CI_ACCESS_TOKEN }}
